"""initial migration

Revision ID: 326cbe78d5c9
Revises: 
Create Date: 2025-02-04 00:59:33.073164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = '326cbe78d5c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id_agent_base', UUID(as_uuid=True), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('companyType', sa.String(), nullable=True),
    sa.Column('actualAddress', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('legalTitle', sa.String(), nullable=True),
    sa.Column('legalLastName', sa.String(), nullable=True),
    sa.Column('legalFirstName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('legalAddress', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_agent_base'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('assortment',
    sa.Column('position_id', UUID(as_uuid=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('pathname', sa.String(), nullable=False),
    sa.Column('paymentitemtype', sa.String(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('variantscount', sa.Float(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('reserve', sa.Float(), nullable=False),
    sa.Column('intransit', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('price_distr', sa.Float(), nullable=False),
    sa.Column('price_opt', sa.Float(), nullable=False),
    sa.Column('price_proiz', sa.Float(), nullable=False),
    sa.Column('price_rrz', sa.Float(), nullable=False),
    sa.Column('price_site', sa.Float(), nullable=False),
    sa.Column('price_tech', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('position_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id_stock_base', UUID(as_uuid=True), nullable=False),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('inTransit', sa.Float(), nullable=True),
    sa.Column('reserve', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('stockDays', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_stock_base')
    )
    op.create_table('sales',
    sa.Column('id_sale', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('moment', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('sum', sa.Float(), nullable=False),
    sa.Column('vatSum', sa.Float(), nullable=False),
    sa.Column('payedSum', sa.Float(), nullable=False),
    sa.Column('shippedSum', sa.Float(), nullable=False),
    sa.Column('invoicedSum', sa.Float(), nullable=False),
    sa.Column('reservedSum', sa.Float(), nullable=False),
    sa.Column('assortment_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('shipmentAddress', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['assortment_id'], ['assortment.id'], ),
    sa.PrimaryKeyConstraint('id_sale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('stock')
    op.drop_table('assortment')
    op.drop_table('agents')
    # ### end Alembic commands ###
